=== Iteracia/travian-bot/resources/command.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="commands">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="command"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="command">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="1">
                <xs:element ref="from" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="to" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="resources" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="troop" minOccurs="0" maxOccurs="10"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:int" use="required"/>
            <xs:attribute name="type" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="from" type="xs:int"/>

    <xs:element name="to">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="1">
                <xs:element name="x"/>
                <xs:element name="y"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="resources">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="1">
                <xs:element name="wood" type="xs:int" maxOccurs="1"/>
                <xs:element name="clay" type="xs:int" maxOccurs="1"/>
                <xs:element name="iron" type="xs:int" maxOccurs="1"/>
                <xs:element name="grain" type="xs:int" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="troop">
        <xs:complexType>
            <xs:attribute name="id" use="required"/>
            <xs:attribute name="count" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Iteracia/travian-bot/commands.xml
<?xml version="1.0" encoding="utf-8"?>
<commands xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="./resources/command.xsd">
    <command type="Market" id="2">
        <from>2</from>
        <to>
            <x>31</x>
            <y>-85</y>
        </to>
        <resources>
            <wood>1000</wood>
            <clay>1000</clay>
            <iron>1000</iron>
            <grain>1000</grain>
        </resources>
    </command>
</commands>
